#!/usr/bin/bash 

cat user_list |grep False |while read line
 do
 user_id=$(echo $line |awk -F "|" '{print $2}')
 domain_id=$(echo $line |awk -F"|"  '{print $7}')
 user_name=$(echo $line |awk -F"|"  '{print $3}')
 project_id=$( grep $domain_id proj_list|head -1| awk -F "|" '{print $2}')
#echo user_id= $user_id  domain_id= $domain_id project_id= $project_id
echo symp -k -u admin -p admin -d cloud_admin  user create --domain-id $domain_id $project_id $user_name "Zaq1@wsx"

 done
